// <auto-generated />
using CarBuyKaro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarBuyKaro.Migrations
{
    [DbContext(typeof(CarBuyKaroContext))]
    partial class CarBuyKaroContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarBuyKaro.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Car_age")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Car_base_price")
                        .HasColumnType("int");

                    b.Property<int>("Car_ins")
                        .HasColumnType("int");

                    b.Property<int>("Car_insurence_price")
                        .HasColumnType("int");

                    b.Property<int>("Car_no")
                        .HasColumnType("int");

                    b.Property<int>("Car_tax")
                        .HasColumnType("int");

                    b.Property<string>("Image_Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Selling_price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Card");
                });
#pragma warning restore 612, 618
        }
    }
}
